### PR TITLE
Apple's Website Webpage Clone

### PR DESCRIPTION
**Pull request by acushlakoncept**
I have successfully finished making a clone of an old version of the Apple website webpage (2014).
> In the course of building the webpage, I have been able to master the concept of using images as a background and adding gradients to elements.
> I learned to size and position the page using correct semantic HTML elements appropriately.
> Correctly setting up the navigation bar.
> Played around with media queries to work a bit on the site responsiveness even though the original isn't.

### CODE REVIEW

**Comment by addod19** [comment]
## Pull Request under review by Daniel Larbi Addo (TSE)

**Comment by addod19** [comment]
## Pull Request under review by Daniel Larbi Addo (TSE)

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes :recycle: :traffic_light: 

Hi @acushlakoncept, congratulations on this project :+1: I realized you implemented a responsive design for this project, although it is not a requirement:smile:  However, there are a few changes we need to implement, kindly find comments below:
- Let us fix the ```.heading-primary``` text, it is overflowing with the nav
txt
- Since this project is mainly about ```Using backgrounds and gradient```, let us make a little change here. Each of the four elements ```<div>``` should be wrapped with ```<a>``` tag, give each of the divs a class, and apply a background image to their respective divs
txt1
- Kindly fix the live link in the README  file
- There are a couple of repeating codes in our CSS file, for instance, ```width:100%``` appears more than 5times. Kindly apply the DRY rule

Kindly make these changes and submit another code review :smile: 
_Happy coding_ :man_technologist: 
Daniel Larbi Addo on slack

**Comment by acushlakoncept** [comment]
Thank you @addod19  for the reviews, I have gone ahead to fix the issues, however about the live link, the one on the branch I am currently working on works. Since I am yet to merge to master, please refer to feature-home branch.

Thank you!

**Comment by lekegitrepo** [comment]
#### Hi @acushlakoncept :clap: :clap:
#### You have done a good job by implementing the required changes. This project is approved.

#### Optional:
**_Try to move the navbar a little up._**

### Reviewed by Temitayo Adeleke.

- Github: [@lekegitrepo](https://github.com/lekegitrepo)
- Twitter: [@leketemi](https://twitter.com/leketemi)
- Linkedin: [linkedin](https://www.linkedin.com/in/temitayo-adeleke/)

**Review by lekegitrepo — APPROVED** [review]
#### Status: Approved.

**Comment by acushlakoncept** [comment]
Thank you @addod19 @lekegitrepo @lekegitrepo for your wonderful reviews.

**Pull request merged**
